# this config is referred from https://github.com/golangci/golangci-lint/blob/v1.23.8/.golangci.yml
run:
  deadline: 1200s
  tests: false

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - paramTypeCombine
      - unnamedResult
  goimports:
    local-prefixes: github.com/dashjay/dbolt
  golint:
    min-confidence: 0
  govet:
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus).Infof
          - (github.com/sirupsen/logrus).Warnf
          - (github.com/sirupsen/logrus).Debugf
          - (github.com/sirupsen/logrus).Errorf
          - (github.com/sirupsen/logrus).Fatalf
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - goconst
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - typecheck
    - unconvert
    - whitespace
    - gocritic
    - staticcheck
    - stylecheck

    # maybe rigorous
    - exhaustive
    - noctx
    - goconst
    - errcheck
    - gocyclo
    - unparam
    - dupl
    - gosec
    - gochecknoglobals
    - godox
    - prealloc
    - unused
    - gochecknoinits
    - nakedret
    - gocognit
    - gomnd
    - funlen
